### ISSUE TITLE
Tries to bootstrap empty node name...ignores specified host

### ISSUE THREAD

**Issue by williamsjj** [higanworks/knife-zero#30]
Installed via `chef gem install knife-zero` (version 1.5.0) 

When I try to bootstrap a remote machine it doesn't pickup the remote machine's name:

```
$  knife zero bootstrap chefserver1.example.com
Node  exists, overwrite it? (Y/N)
ERROR: Method Not Allowed
Response: Bad request method for '': DELETE
```

**Comment by sawanoboly** [comment]
You look like tried to [Validatorless Bootstraps](https://www.chef.io/blog/2015/04/16/validatorless-bootstraps/) ?

**Comment by sawanoboly** [comment]
Or, if you use chef-vault ? Then we must pass a node name with -N, see below.

https://github.com/chef/chef/blob/master/lib/chef/knife/bootstrap.rb#L320-L323

**Comment by williamsjj** [comment]
I am bootstrapping with 12.3.0. Does Zero require a validator setup?

On May 23, 2015, at 3:17, "Yukihiko SAWANOBORI" <notifications@github.com<mailto:notifications@github.com>> wrote:


You look like tried to Validatorless Bootstraps<https://www.chef.io/blog/2015/04/16/validatorless-bootstraps/> ?

-
Reply to this email directly or view it on GitHub<https://github.com/higanworks/knife-zero/issues/30#issuecomment-104872588>.

!SIG:556045a531602191413642!

**Comment by sawanoboly** [comment]
> Does Zero require a validator setup?

No, it doesn't. That is chef's change. I think that error was caused by chef's change.

Did you set Chef::Config[:validation_key] to knife.rb ?
If exist, could you please try to bootstrap without --name option after remove line of validation_key from knife.rb ?

The chef checks existence of a node when applies to conditions below.

- doing_chef_vault
- Chef::Config has [:validation_key] option, but validation_key doesn't exist at real path.

In this case, requires --name option.
