### ISSUE TITLE
Policyfiles

### ISSUE THREAD

**Issue by epcim** [higanworks/knife-zero#79]
Are the policyfiles in the scope? [FEATURE]

During bootstrap/converge to be able to provide '-n' attribte and specify named_runlist from policyfile, and the policy file itself (or Policyfile.lock.json in the main dir.) - similary to what '-r' option serve for.

Note, 
- supposing chef-zero support policyfiles

**Comment by sawanoboly** [comment]
Yes, I'm going to try to support policyfiles when its state has been became stable.

Could you show me current workflow and Policyfile examples which you using ? It is all right with a simple content.

**Comment by sawanoboly** [comment]
Ah, I'll manage. 

I have to adding few configuration both local knife.rb and remote client.rb. And I've understood that `chef export` helps supporting PolicyFiles with knife-zero.

I'll do sometime next week, maybe.

**Comment by sawanoboly** [comment]
hmm.. I've checked what is needed how to support policyfiles now.

- OK: chef-zero supports policy_document_native_api.
- UNKNOWN: I seem to `chef exports` doesn't create structure of policy_document_native_api yet.

Even if I'll implement without supporting policy_document_native_api, I have to update to support policy_document_native_api in near future probably.

**Comment by sawanoboly** [comment]
@epcim

Could you test #80 ? I've implemented databag style (use deployment_group).

I've refered to https://github.com/chef/chef-dk/blob/master/lib/kitchen/provisioner/policyfile_zero.rb .

**Comment by sawanoboly** [comment]
included in 1.13.0.

**Comment by epcim** [comment]
thx.. will have a look soon

**Comment by zedtux** [comment]
@sawanoboly I'm using policyfiles and I'm facing some issues, I guess it is _just_ a matter of understanding on my side.

## The Chef repo

Given a chef repo with a `knife.rb` file with the following :

```ruby
chef_repo_path              File.expand_path('../' , __FILE__)
local_mode                  true
policy_document_native_api  false
use_policyfile              true
versioned_cookbooks         true

...

knife[:automatic_attribute_whitelist] = %w[
  fqdn
  ...
]
```

And a policyfile `policyfiles/k8smaster.rb` with the following :

```ruby
# Policyfile.rb - Describe how you want Chef to build your system.
#
# For more information on the Policyfile feature, visit
# https://docs.chef.io/policyfile.html

# A name that describes what the system you're building with Chef does.
name 'k8smaster'

# Where to find external cookbooks:
default_source :supermarket

# run_list: chef-client will run these recipes in the order specified.
run_list 'recipe[ssh-keys]'

# Specify a custom source for a single cookbook:
# cookbook 'example_cookbook', path: '../cookbooks/example_cookbook'

cookbook 'ssh-keys', '~> 1.2.7'

default['ssh_keys'] = {
  root: 'root'
}
```

And a data bag at `data_bags/users/root.json`
And finally my `README.md` file with all the instructions and so on.

## The workflow

I then run a `chef install policyfiles/k8smaster.rb` which generates the `policyfiles/k8smaster.lock.json` file.

Now I don't want to loose my `README.md` file and get the mess of the `chef export` command, so I'm doing `chef export policyfiles/k8smaster.rb ./dist -f` so that all the things to be synced with the remote server is packed within a single folder that I can ignore from the `.gitignore` file.

As I'm using a sub folder with the export sub command :

 - If I run the `bootstrap` or `converge` from the chef repo folder, it crashes with the error
  ```
  Chef::PolicyBuilder::Policyfile::ConfigurationError: Error loading policyfile from `policy_groups/local/policies/k8smaster': Net::HTTPServerException - 404 "Not Found "
  ```
- If I run the `bootstrap` or `converge` from the `dist/` folder, it crashes because the `ssh-keys` cookbook can't find the data_bags
 - If I copy the `data_bags/` folder from the chef repo to the `dist/` folder, and I run the `bootstrap` or `converge` from the `dist/` folder, then it works, but the node JSON file is saved in `dist/nodes/` so I'm loosing it.

## Conclusion

To avoid all of those problems, I would have to not set a sub folder to the `chef export` command, but then :
 - I'm loosing my `README.md` file
 - I'm then having a `cookbook_artifacts`, `policies` and `policy_groups` folder, plus a `Policyfile.lock.json` (which I don't want to version, so I would have to add them to the `.gitignore` file)

Using a sub folder to the `chef export` command (as told on https://learn.chef.io/modules/managing-nodes-with-policyfiles#/infrastructure-automation) solve the above issue, but I'm having the data bag issue and I'm missing the `nodes/` folder update.

## Questions

1. I saw in the #80 PR that you're mentioning something about `deployment_group` related to data_bags, but I can't figure out how to set it properly. So how can I solve the missing data bag issue from the `dist/` folder?
2. How to get the `nodes/` folder update out of the `dist/` folder?
3. If the way I'm using Chef Zero is wrong, what is the proper use of Chef Zero with Policyfiles, and having a `README.md` file?

Sorry for the long comment 😞. I wasn't sure to have to open a new issue ...

**Comment by sawanoboly** [comment]
Thank you for the detailed report. @zedtux 

I usually do not use policy files. The support in this plug-in is in line with quite early specs.
I think the specs have changed since that time.

Can you register as a new issue? However, I do not have time for a while, so I do not know if I can handle it.

**Comment by zedtux** [comment]
Thank you @sawanoboly for your answer.

I will open a new issue, no problem.

Can you juste tell me about this `deployment_group` please ? Could it solve the issue that the `data_bags/` is not included in the output of `chef export` or not?
